### PR TITLE
Android app

### PR DESCRIPTION
**Pull request by madhavc**
I have started working on the Android App and I needed to get some feedback from you on the design work. I am trying to make the Android App design similar to the iOS designs. Will you kindly review the app and give me some feedback on if this an acceptable Android App. If Parse Design team have designs they want me to use for the Android App please let me know. 

Thank you

### CODE REVIEW

**Comment by madhavc** [comment]
@hramos @gfosco

**Comment by gfosco** [comment]
I like it... Great work on this and others might find it valuable.  Ping me again when you're ready with a complete version and I think we can accept it.

**Comment by madhavc** [comment]
Thanks @gfosco I will continue working on this.

**Comment by madhavc** [comment]
@gfosco Please test and merge. Side note some UI components can be improved by replacing the old ones with new ones from your design team. Thank you!

**Comment by gfosco** [comment]
Cool, this is great.  Thanks! :+1:

**Pull request merged**
